SCAN_SESSIONS_COLLECTION = "scan_sessions"
SCAN_JOBS_COLLECTION = "scan_jobs"
FINDINGS_COLLECTION = "findings"
FIX_SUGGESTIONS_COLLECTION = "fix_suggestions"
VERIFICATION_RUNS_COLLECTION = "verification_runs"
AUDIT_EVENTS_COLLECTION = "audit_events"
REPORT_EXPORTS_COLLECTION = "report_exports"

REQUIRED_COLLECTIONS = (
    SCAN_SESSIONS_COLLECTION,
    SCAN_JOBS_COLLECTION,
    FINDINGS_COLLECTION,
    FIX_SUGGESTIONS_COLLECTION,
    VERIFICATION_RUNS_COLLECTION,
    AUDIT_EVENTS_COLLECTION,
    REPORT_EXPORTS_COLLECTION,
)
