SCAN_SESSIONS_COLLECTION = "scan_sessions"
SCAN_JOBS_COLLECTION = "scan_jobs"
FINDINGS_COLLECTION = "findings"
VERIFICATION_RUNS_COLLECTION = "verification_runs"
AUDIT_EVENTS_COLLECTION = "audit_events"
RUNTIME_SETTINGS_COLLECTION = "runtime_settings"

REQUIRED_COLLECTIONS = (
    SCAN_SESSIONS_COLLECTION,
    SCAN_JOBS_COLLECTION,
    FINDINGS_COLLECTION,
    VERIFICATION_RUNS_COLLECTION,
    AUDIT_EVENTS_COLLECTION,
    RUNTIME_SETTINGS_COLLECTION,
)
